name: AgendeMe-WEB CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    environment:
      name: Produção
    
    env:
      work-directory-web: Codigo/AgendeMeWeb
      #work-directory-core: Codigo/Core
      #work-directory-service: Codigo/Service

    steps:
    - name: Execute checkout in repository
      uses: actions/checkout@v2
    
    - name: Configure .NET version
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.417
      
    - name: Replace variables for AgendeMeWeb
      uses: microsoft/variable-substitution@v1
      with:
        files: '${{env.work-directory-web}}/appsettings.json'
      env:
        ConnectionStrings.AgendeMeDatabase: ${{secrets.FTP_DATABASE_CONNECTION_STRING}}

    - name: Restore dependencies for AgendeMeWeb
      run: |
        cd ${{env.work-directory-web}}
        dotnet restore

    - name: Build and Publish AgendeMeWeb
      run: |
        cd ${{env.work-directory-web}}
        dotnet build --no-restore ./AgendeMeWeb.csproj
        dotnet publish -c Release --no-restore -o ./publishWEB ./AgendeMeWeb.csproj
    
    - name: Upload AgendeMeWeb via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASS }}
        local-dir: '${{env.work-directory-web}}/publishWEB/'
        remote-dir: ./AgendeMeWeb
        exclude: |
          **/.git*
          **/.git*/**
          **/AnaliseProjeto

    # - name: Restore dependencies for AgendeMeCore
    #   run: |
    #     cd ${{env.work-directory-core}}
    #     dotnet restore

    # - name: Build and Publish AgendeMeCore
    #   run: |
    #     cd ${{env.work-directory-core}}
    #     dotnet build --no-restore ./Core.csproj
    #     dotnet publish -c Release --no-restore -o ./publishCORE ./Core.csproj
    
    # - name: Upload AgendeMeCore via FTP
    #   uses: SamKirkland/FTP-Deploy-Action@4.3.0
    #   with:
    #     server: ${{ secrets.FTP_SERVER }}
    #     username: ${{ secrets.FTP_USER }}
    #     password: ${{ secrets.FTP_PASS }}
    #     local-dir: '${{env.work-directory-core}}/publishCORE/'
    #     remote-dir: ./AgendeMeCore
    #     exclude: |
    #       **/.git*
    #       **/.git*/**
    #       **/AnaliseProjeto

    # - name: Restore dependencies for AgendeMeService
    #   run: |
    #     cd ${{env.work-directory-service}}
    #     dotnet restore

    # - name: Build and Publish AgendeMeService
    #   run: |
    #     cd ${{env.work-directory-service}}
    #     dotnet build --no-restore ./Service.csproj
    #     dotnet publish -c Release --no-restore -o ./publishSERVICE ./Service.csproj
    
    # - name: Upload AgendeMeService via FTP
    #   uses: SamKirkland/FTP-Deploy-Action@4.3.0
    #   with:
    #     server: ${{ secrets.FTP_SERVER }}
    #     username: ${{ secrets.FTP_USER }}
    #     password: ${{ secrets.FTP_PASS }}
    #     local-dir: '${{env.work-directory-service}}/publishSERVICE/'
    #     remote-dir: ./AgendeMeService
    #     exclude: |
    #       **/.git*
    #       **/.git*/**
    #       **/AnaliseProjeto
